export { default as Arrow } from "./arrow";
export { default as Instagramm } from "./instagramm";
export { default as Phone } from "./phone";
export { default as Location } from "./location";
export { default as Time } from "./time";
export { default as Gis2 } from "./2gis";
export { default as Arrow2 } from "./arrow2";
export { default as WatsappColor } from "./watsapp color";
export { default as Watsapp } from "./watsapp1";
export { default as Youtube } from "./youtube";
export { default as Play } from "./play";
export { default as Rectangle } from "./rectangle";
export { default as Correct } from "./correct";